### ISSUE TITLE
nonce

### ISSUE THREAD

**Issue by moonlitknight** [warren-bank/node-kraken-api#1]
More of a heads-up than a bug...

I found I was getting several "Nonce: error" when I was retrying a timed-out transaction. The reason was the library was silently setting a default value for `params.nonce` on the first invocation. On the retry invocations, the `if (!params.nonce)` test was failing because the previously generated nonce was still instantiated in `params`.

My local workaround has been to remove the `if (!params.nonce)` condition, thus making the library generate a new nonce for every call. 

My preference would be to use a new signalling property `params.appNonce` and have the condition read
```
if (params.appNonce) {
  params.nonce = params.appNonce;
} else {
 params.nonce = new Date() * 1000; // spoof microsecond
}
```

however that would be a breaking change. 

A more complex (risky?) change would be to flag internally that a default nonce had been generated and unset it before returning control to the calling app.

**Comment by warren-bank** [comment]
Hi, I honestly didn't suspect than anybody would be using this library; it's really just a light-weight wrapper around the upstream library.

I wrote it at a time when I was interested in learning a bit more about the various crypt-currency exchanges, and before I wrote a more [general-purpose solution](https://github.com/warren-bank/node-denodeify) to wrap (ie: denodeify) functions to coerce (ie: promisify) them to return a Promise. Had that library already existed, I probably (almost certainly) wouldn't have bothered to create a fork.

for example (untested, just off the top of my head):
``` javascript
// https://github.com/nothingisdead/npm-kraken-api
// https://github.com/warren-bank/node-denodeify

const KrakenClient = require('kraken-api')
const denodeify = require('@warren-bank/node-denodeify').denodeify

const kraken = new KrakenClient('api_key', 'api_secret')
const krakenAPI = denodeify(kraken.api, kraken)

krakenAPI('Ticker', {"pair": 'XBTCXLTC'})
.then((data) => {
  console.log(data.result)
})
.catch((error) => {
  console.log(error.message)
})
```

Anyway, to the point at hand..
Am I'm understanding your use-case:
  * your app uses this library to make API calls
  * each initial API call doesn't specify any `params.nonce`, so the library generates one that's based on the timestamp that the request is made
    * note to self: change `new Date() * 1000` to `Date.now() * 1000`.. that just irritates me
  * if the initial API call times out, then your app catches the error and re-attempts a subsequent API call which DOES specify a value for `params.nonce`.. and this value is <= the nonce last used (ie: potentially in a completely unrelated API call.. since the `nonce` must always be increasing.. as seen from the standpoint of the web service receiving such requests)

There must be something else going on, because that usage pattern that I just described is rather odd.

Off-hand, I'd say that the nonce should either always be generated by the library.. OR it should always be generated by your app. Mixing the two assumes that they both use the same methodology for generating an always increasing integer value. Personally, had I written the this implementation from scratch (rather than forking it).. I wouldn't have included an option to allow the nonce to be specified.. that can only lead to bad things.

That being said, the way that the implementation auto-generates its `nonce` seems (to me) to be less than ideal. If more than one API request occurs per second, then those multiple requests would all be sent using the same `nonce`.. which IS a rather important bug. I'll probably patch.. since I hate putting my name on code with such a glaring omission.

Anyway, back to your use-case.. is there a legitimate reason that your app is generating its own `nonce` value for the re-attempted API calls (rather than allowing the library to auto-generate a new one)?

here's another quick (untested) rewrite of that above example w/ support for retry:
``` javascript
// https://github.com/nothingisdead/npm-kraken-api
// https://github.com/warren-bank/node-denodeify

const KrakenClient = require('kraken-api')
const denodeify = require('@warren-bank/node-denodeify').denodeify

const kraken = new KrakenClient('api_key', 'api_secret')
const krakenAPI = denodeify(kraken.api, kraken)

const krakenAPI_with_retry = function(method, params) {
  return krakenAPI(method, params)
  .catch((error) => {
    if (error.code === 'ECONNRESET') return krakenAPI_with_retry(method, params)
    else throw error
  })
}

krakenAPI_with_retry('Ticker', {"pair": 'XBTCXLTC'})
.then((data) => {
  console.log(data.result)
})
.catch((error) => {
  console.log(error.message)
})
```

**Comment by moonlitknight** [comment]
Hi Warren

Thx for the response. Yours looked better maintained than the upstream, plus I like Promises :-) so I'm using your fork. I'm certainly not expecting you to support it, but felt it worth posting the issue as a heads up in case it bites anybody.

On your interpretation of my use case, your first two bullets are correct. (I also made the change to Date.now() for much the same reason :-) )
On your third bullet, as far as my app is concerned, I never **knowingly** provide a value to params.nonce. However **I do reuse** the same params object. The issue is that on subsequent retries, the params object has been polluted with the initially generated nonce, and therefore fails.

**Comment by warren-bank** [comment]
ohh.. now I totally see what you mean. Your `params` object was passed by reference into the function, which then added attributes (ex: `params.nonce`). Later, when the same `params` object was re-used and passed (again, by reference) to the same function, it detected that `params.nonce` did (in fact) have a value.. and it reused it.. because the original API allowed the user to manually specify their own.

I just pushed a v3.0.0, which disallows this behavior. It still adds a few attributes to the `params` object, but nothing that would cause a problem with future re-use.

I suppose it would be cleaner to clone the object before touching it (ie: `params = Object.assign({}, params)`).. but at this point.. there's no need. Do you agree?

Thanks for the heads up!

**Comment by warren-bank** [comment]
PS) before pushing these changes, while I was re-running the tests (ie: calling public API methods).. I was seeing a high frequency (maybe 1 in every 20) of responses that contain an HTML page describing a server timeout, rather than sending a JSON string.

This would (of course) trip up the JSON parser.. causing it to throw an error. Since this is something that is important to test for, I gave this particular error a code: `error.code === 'JSON-PARSE'`. Also, purely for debugging purposes, when the code is set.. the entire HTML text dump is available on the error object at: `error.api_response`.

**Comment by warren-bank** [comment]
sanitized:

```text
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="set-cookie" content="cf_use_ob=0; expires=Mon, 03-Jul-17 00:39:25 GMT; path=/">
<title>api.kraken.com | 504: Gateway time-out</title>
<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
<meta name="robots" content="noindex, nofollow"/>
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/>
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection"/>
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type" data-translate="error">Error</span>
<span class="cf-error-code">504</span>
<small class="heading-ray-id">Ray ID: 1234567890abcdef &bull; 2017-07-03 00:38:55 UTC</small>
</h1>
<h2 class="cf-subheadline" data-translate="error_desc">Gateway time-out</h2>
</div> 
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc" data-translate="browser_desc">You</span>
<h3 class="cf-status-name" data-translate="browser_label">Browser</h3>
<span class="cf-status-label" data-translate="browser_status_label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc" data-translate="cloud_desc">Here</span>
<h3 class="cf-status-name" data-translate="cloud_label">Cloudflare</h3>
<span class="cf-status-label" data-translate="cloud_status_label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc" data-translate="server_desc">api.kraken.com</span>
<h3 class="cf-status-name" data-translate="server_label">Host</h3>
<span class="cf-status-label" data-translate="server_status_label">Error</span>
</div>
</div>
</div>
</div> 
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2 data-translate="what_happened">What happened?</h2>
<p>The web server reported a gateway time-out error.</p>
</div>
<div class="cf-column">
<h2 data-translate="what_can_i_do">What can I do?</h2>
<p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>
</div>
</div>
</div> 
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>1234567890abcdef</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 127.0.0.1</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div> 
</div> 
</div>
```

**Comment by moonlitknight** [comment]
Changes look good.
I'm currently dealing with the annoying CloudFlare HTML at the app level, so for me it's a breaking change. No problem with that, but it will be a day or so before I can revise my timeout error handling and test.
I'll add an update, by Wed, but thx in the meantime.

**Comment by moonlitknight** [comment]
Working well.

One parting heads-up. I've changed the 5000 http timeout to 20000 as Kraken is very slow these days.

**Comment by warren-bank** [comment]
That's great, I'm glad you like. And totally agree.. a 5 second timeout is a bit strict. Next time I push any changes for this repo, I'll be sure to bump up the default value for the "timeout" option.
